package it.beyondthecube.domino.terrain;

public enum AreaType {
	NONE, MINE, SAWMILL, FARM, MINT, TOWNHALL, MARKET, DOCK, EMBASSY, SMITH, BAKERY, BANK, STABLE, BARRACK, WALL, LABORATORY, MAGIC_TOWER, SHOOTING_RANGE, TRIBUNAL, SHIPYARD, UNIVERSITY, MUSEUM, TEMPLE, LIBRARY, GUILD_HALL, WINDMILL, SMELTERY, SIEGEWORK, GRAVEYARD
}
